### import 
``` 
	import statsmodels
	import numpy as np
	import matplotlib.pylab as plt
```

In [1]:
import statsmodels
import numpy as np
import matplotlib.pylab as plt

### 1. create a matrix (numpy array) of ones sized (100 X 50) 

`use .shape to check your matrix`

In [4]:
ones5000 = np.ones((100,50))
ones5000.shape

(100, 50)

### 2. create a matrix of zeros the same size as the matrix from (1)
`use numpy`

In [8]:
zeros5000 = np.zeros((100,50))
zeros5000.shape

(100, 50)

### 3. create a new matrix that will be the concatenation of (1 & 2) --> matrix sized (200, 50)

In [9]:
concat_one_zero = np.concatenate((ones5000, zeroes5000))
concat_one_zero.shape

(200, 50)

### 4. Add the two matrices (from 1 & 2) to get one matrix (100 X 50) --> check yourself (do all enteries show 1?)

In [13]:
sum_matrix = ones5000 + zeros5000
sum_matrix

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

### 5. Use the function we have created few warm-ups ago to create two matrices 20X40 from multivariate normal distribution

In [39]:
mean = [0,0]
cov = [[1,0],[0, 1]]

x, y = np.random.multivariate_normal(mean, cov, (40, 20)).T
print(x.shape)
print(y.shape)

(20, 40)
(20, 40)


In [15]:
norm_matrix_1 = np.random.normal(size=(20, 40))
norm_matrix_2 = np.random.normal(size=(20, 40))

norm_matrix_1

array([[ 1.13826201e-01,  1.84892707e+00,  1.48648734e+00,
         2.22190950e+00, -5.55341948e-01,  3.33796932e-01,
        -2.13113709e+00,  2.06870487e+00,  6.86845855e-01,
        -1.63046706e-01, -2.63076423e-01, -1.33707769e+00,
        -2.20207437e-01, -6.86215612e-01, -1.04065798e+00,
        -9.06534049e-01, -1.14056606e+00,  1.72776452e+00,
        -3.97539985e-01, -1.00261762e+00,  4.50243911e-01,
        -1.35659118e+00,  2.87902979e-01,  4.09803373e-02,
        -3.21139513e-01,  8.00539839e-02,  5.46683407e-01,
         8.84162006e-01,  1.86436292e-01, -1.42291896e-01,
         4.36059841e-01, -6.73030808e-03, -3.59180263e-01,
        -9.35955543e-01,  1.65392314e-01,  8.69503254e-01,
         9.49775742e-01,  1.33704806e-01,  1.67635310e+00,
        -9.50443271e-01],
       [-4.02827434e-01,  9.88149407e-01, -2.81386838e+00,
         1.15878520e+00, -8.04208075e-01, -1.05290936e-01,
        -1.30126752e-01, -2.07667017e+00, -7.93485301e-01,
         2.25484272e+00, -9.51

### 6. let's try to make two operations: 
    # - matrix multiplication (first test it on a 2X2 matrices)
    # - element wise multiplication 

In [23]:
a = np.array([[1, 2], [3, 4]])


matrix_multiply = np.matmul(a, a)
print(matrix_multiply)


element_multiply = a * a
print(element_multiply)

[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]


### 7. let's create again the linear equations Y = XW + noise
##### Noise should come from univariate normal distribution with mean 0 and variance 0.1 

### 8. Can you calculate the weight (coeficients) matrix? Do it.
### Write down the equation of the multiple regression model

### 9. Create a function that calculates the mean squared error 

### 10. Plot the errors to check for normality

### 11. Plot scatter plots of the independent variables against the target value to check for violations of the constant variance assumption for errors 

### 12. Calculate R squared (you can use statsmodels)